name: Release to DockerHub
on:
  release:
    types: [published]

jobs:
  release:
    name: Build and push docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Show release version
        run: echo ${{ github.event.release.tag_name }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64 #, linux/arm/v6, linux/arm/v7,
          push: true
          tags: riscvcourse/workshop_risc-v:latest, riscvcourse/workshop_risc-v:${{ github.event.release.tag_name }}
